// Screenshot metadata — images populated when extract-screenshots.mjs is run.
export const docScreenshots: Record<string, { num: number; caption: string; details: string[]; image: string }[]> = {
  'module-login': [
    { num: 1, image: "", caption: "Login page — Flowentra sign-in screen", details: ["Email and password fields", "Sign In button", "Forgot password link"] },
  ],
  'module-dashboard': [
    { num: 1, image: "", caption: "Dashboard home — default landing view", details: ["KPI widget row", "Built-in dashboard switcher", "Period selector"] },
    { num: 2, image: "", caption: "First-time user product tour welcome", details: ["28-step guided tour", "Skip or continue options"] },
    { num: 3, image: "", caption: "Dashboard builder — widget canvas", details: ["Drag and drop widgets", "Grid layout controls"] },
    { num: 4, image: "", caption: "Widget type picker", details: ["14 widget types", "KPI, Bar, Line, Pie, Map and more"] },
    { num: 5, image: "", caption: "Dashboard settings panel", details: ["Auto-refresh toggle", "Card style, spacing, animation"] },
  ],
  'module-contacts': [
    { num: 1, image: "", caption: "Contacts list — KPI header and table", details: ["Search and filter bar", "Person / Company / Supplier tabs"] },
    { num: 2, image: "", caption: "Contact detail — 360 tabs", details: ["Installations, Offers, Sales, Service Orders, Purchases, Notes"] },
    { num: 3, image: "", caption: "Dynamic import — column mapping", details: ["Excel header mapping", "Duplicate strategy selector"] },
    { num: 4, image: "", caption: "Advanced filters panel", details: ["Status, Type, Tags, Favorites filters"] },
    { num: 5, image: "", caption: "Contact map view — geolocation pins", details: ["Interactive map", "Open in Maps navigation"] },
  ],
  'module-articles': [
    { num: 1, image: "", caption: "Articles list — catalog overview", details: ["Table and grid view toggle", "Category and type filters"] },
    { num: 2, image: "", caption: "Article detail — pricing and stock fields", details: ["Selling price HT, Cost, Margin, VAT", "Min/Max stock thresholds"] },
    { num: 3, image: "", caption: "Stock transactions log", details: ["Date, type, quantity, before/after balance"] },
    { num: 4, image: "", caption: "Bulk import — structured template", details: ["Download template", "Upload and validate"] },
  ],
  'module-stock-management': [
    { num: 1, image: "", caption: "Stock management — warehouse overview", details: ["Gauge cards per article", "Critical / Low / Healthy status"] },
    { num: 2, image: "", caption: "Stock movement — manual adjustment", details: ["Reason picklist", "Single or bulk entry"] },
    { num: 3, image: "", caption: "Inter-warehouse transfer", details: ["Two-step confirm: sent / received"] },
    { num: 4, image: "", caption: "Replenishment proposals list", details: ["Auto-generated draft Purchase Orders", "Low-stock threshold comparison"] },
  ],
  'module-purchases': [
    { num: 1, image: "", caption: "Purchase orders list", details: ["Status: Draft to Received", "Supplier and date filters"] },
    { num: 2, image: "", caption: "Purchase order detail — line items", details: ["Multi-line PO", "Payment terms, fiscal stamp, auto totals"] },
    { num: 3, image: "", caption: "Goods receipt — partial reception", details: ["Received qty per line", "Automatic stock movement created"] },
    { num: 4, image: "", caption: "Supplier invoice — 3-way match", details: ["PO vs Receipt vs Invoice", "Retenue a la source auto-computed"] },
    { num: 5, image: "", caption: "Fiscal compliance dashboard", details: ["RS YTD, Facture en Ligne counts, TEJ sync"] },
    { num: 6, image: "", caption: "Supplier performance report", details: ["On-time delivery %, avg lead time, total spend"] },
  ],
  'module-service-orders': [
    { num: 1, image: "", caption: "Service orders list — table view", details: ["Status flow from Pending to Closed", "Search and advanced filters"] },
    { num: 2, image: "", caption: "Service order detail — overview tab", details: ["Client, installation, priority, description"] },
    { num: 3, image: "", caption: "Jobs tab — grouped by installation", details: ["Job title, code, status, work type"] },
    { num: 4, image: "", caption: "Dispatches tab", details: ["Dispatch number, technician, scheduled date/time, priority"] },
    { num: 5, image: "", caption: "Time and Expenses log", details: ["Linked to source dispatch", "Hours, cost entries"] },
    { num: 6, image: "", caption: "Materials used tab", details: ["Articles deducted from stock catalog"] },
    { num: 7, image: "", caption: "Service order map view", details: ["Geolocation pins", "Open in Maps navigation"] },
  ],
  'module-hr': [
    { num: 1, image: "", caption: "Employee directory", details: ["Payroll-readiness segmentation", "Search and department filter"] },
    { num: 2, image: "", caption: "Payroll run — monthly summary", details: ["CNSS, CSS, IRPP brackets", "PDF payslip generation"] },
    { num: 3, image: "", caption: "Attendance matrix view", details: ["Worked hours, overtime, late count per employee"] },
    { num: 4, image: "", caption: "Leave request workflow", details: ["Calendar view", "Manager approval flow"] },
    { num: 5, image: "", caption: "CNSS declaration — monthly export", details: ["CSV export for CNSS portal", "Rates per employee"] },
    { num: 6, image: "", caption: "Org chart — department hierarchy", details: ["Manager avatars", "Hierarchical tree"] },
    { num: 7, image: "", caption: "Recruitment Kanban pipeline", details: ["Applied to Screening to Interview to Offer to Hired"] },
  ],
  'module-dynamic-forms': [
    { num: 1, image: "", caption: "Forms list — draft and released", details: ["Status chips: Draft / Released / Archived", "Public link toggle"] },
    { num: 2, image: "", caption: "Form builder — drag and drop canvas", details: ["15+ field types", "Live preview panel"] },
    { num: 3, image: "", caption: "Form builder — field settings", details: ["Label, placeholder, required, validation"] },
    { num: 4, image: "", caption: "Public form — end-user view", details: ["EN/FR language switcher", "Clean submission UI"] },
    { num: 5, image: "", caption: "Response inbox", details: ["CSV/Excel export", "PDF per response"] },
  ],
  'module-workflow': [
    { num: 1, image: "", caption: "Workflow canvas — React-Flow editor", details: ["Pan/zoom, mini-map, snap-to-grid", "Multi-select, undo/redo"] },
    { num: 2, image: "", caption: "Trigger node configuration", details: ["Webhook, Scheduled CRON, Status-change, Entity-created"] },
    { num: 3, image: "", caption: "Action node — Send Email", details: ["Template editor", "Dynamic field mapping"] },
    { num: 4, image: "", caption: "AI workflow builder", details: ["Natural-language prompt to graph generation"] },
    { num: 5, image: "", caption: "Live execution debugger", details: ["Color-coded nodes", "Input/output JSON per step"] },
    { num: 6, image: "", caption: "Execution history list", details: ["Status, timing, triggered by"] },
  ],
  'module-external': [
    { num: 1, image: "", caption: "External endpoints list", details: ["Unique slug URL per endpoint", "API key management"] },
    { num: 2, image: "", caption: "Endpoint configuration", details: ["Allowed HTTP methods", "Optional JSON Schema validation"] },
    { num: 3, image: "", caption: "Inbound log — payload preview", details: ["Date/time, Method, Source IP, Status code"] },
    { num: 4, image: "", caption: "Convert payload to CRM record", details: ["One-click: Offer / Sale / Contact creation"] },
  ],
  'module-lookups': [
    { num: 1, image: "", caption: "Lookups — two-pane layout", details: ["Left category browser", "Right item list"] },
    { num: 2, image: "", caption: "Category items — add and edit", details: ["Name, active toggle, sort order, default star"] },
  ],
  'module-scheduling': [
    { num: 1, image: "", caption: "Dispatcher — swimlane timeline", details: ["Technician rows x hour columns", "1d to 30d horizons"] },
    { num: 2, image: "", caption: "Monthly calendar view", details: ["Technician avatars per day", "30-day grid"] },
    { num: 3, image: "", caption: "Drag and drop reschedule", details: ["Move job pill to new time slot or technician"] },
    { num: 4, image: "", caption: "Unassigned service orders rail", details: ["Right-side panel with search", "Drag to assign"] },
  ],
  'module-settings': [
    { num: 1, image: "", caption: "Settings — personal profile", details: ["Avatar, display name, language, timezone"] },
    { num: 2, image: "", caption: "Company settings — branding", details: ["Logo, legal name, Tax ID, default currency"] },
    { num: 3, image: "", caption: "Preferences — theme and accent color", details: ["Light / Dark / System theme", "Accent color picker"] },
    { num: 4, image: "", caption: "User management — roles and permissions", details: ["RBAC permission matrix per module"] },
    { num: 5, image: "", caption: "Subscription — plan and billing", details: ["Plan details, usage, billing history"] },
  ],
};
