export const docScreenshotsFr: Record<string, Record<number, { caption: string; details?: string[] }>> = {
  'module-login': {
    1: { caption: "Page de connexion ecran de connexion Flowentra", details: ["Champs email et mot de passe", "Bouton Se connecter", "Lien mot de passe oublie"] },
  },
  'module-dashboard': {
    1: { caption: "Tableau de bord vue d'accueil par defaut", details: ["Ligne de widgets KPI", "Selecteur de tableau de bord integre", "Selecteur de periode"] },
    2: { caption: "Visite guidee du produit pour le premier utilisateur", details: ["Visite guidee en 28 etapes", "Options passer ou continuer"] },
    3: { caption: "Constructeur de tableau de bord canevas de widgets", details: ["Widgets par glisser-deposer", "Controles de grille"] },
    4: { caption: "Selecteur de type de widget", details: ["14 types de widgets", "KPI, Barres, Lignes, Camembert, Carte et plus"] },
    5: { caption: "Panneau de parametres du tableau de bord", details: ["Actualisation automatique", "Style de carte, espacement, animation"] },
  },
  'module-contacts': {
    1: { caption: "Liste des contacts en-tete KPI et tableau", details: ["Barre de recherche et filtres", "Onglets Personne / Entreprise / Fournisseur"] },
    2: { caption: "Detail du contact onglets 360", details: ["Installations, Offres, Ventes, Ordres de service, Achats, Notes"] },
    3: { caption: "Import dynamique mappage de colonnes", details: ["Mappage des en-tetes Excel", "Selecteur de strategie de doublons"] },
    4: { caption: "Panneau de filtres avances", details: ["Filtres Statut, Type, Tags, Favoris"] },
    5: { caption: "Vue carte des contacts epingles de geolocalisation", details: ["Carte interactive", "Navigation Ouvrir dans Maps"] },
  },
  'module-articles': {
    1: { caption: "Liste des articles apercu du catalogue", details: ["Basculer entre vue tableau et grille", "Filtres categorie et type"] },
    2: { caption: "Detail de l'article tarification et stock", details: ["Prix de vente HT, Cout, Marge, TVA", "Seuils stock min/max"] },
    3: { caption: "Journal des transactions de stock", details: ["Date, type, quantite, solde avant/apres"] },
    4: { caption: "Import en masse modele structure", details: ["Telecharger le modele", "Importer et valider"] },
  },
  'module-stock-management': {
    1: { caption: "Gestion des stocks apercu entrepot", details: ["Cartes jauges par article", "Statut Critique / Bas / Normal"] },
    2: { caption: "Mouvement de stock ajustement manuel", details: ["Liste de motifs", "Saisie unitaire ou en masse"] },
    3: { caption: "Transfert inter-entrepots", details: ["Confirmation en deux etapes : envoye / recu"] },
    4: { caption: "Liste des propositions de reapprovisionnement", details: ["Bons de commande brouillons auto-generes", "Comparaison avec stock minimum"] },
  },
  'module-purchases': {
    1: { caption: "Liste des bons de commande", details: ["Statuts : Brouillon a Recu", "Filtres fournisseur et date"] },
    2: { caption: "Detail du bon de commande lignes", details: ["BC multi-lignes", "Conditions de paiement, timbre fiscal, totaux automatiques"] },
    3: { caption: "Bon de reception reception partielle", details: ["Quantite recue par ligne", "Mouvement de stock cree automatiquement"] },
    4: { caption: "Facture fournisseur rapprochement a 3 voies", details: ["BC vs Reception vs Facture", "Retenue a la source calculee automatiquement"] },
    5: { caption: "Tableau de bord conformite fiscale", details: ["RS YTD, compteurs Facture en Ligne, statut TEJ"] },
    6: { caption: "Rapport de performance fournisseurs", details: ["% livraison a temps, delai moyen, depenses totales"] },
  },
  'module-service-orders': {
    1: { caption: "Liste des ordres de service vue tableau", details: ["Flux de statut de En attente a Cloture", "Recherche et filtres avances"] },
    2: { caption: "Detail de l'ordre de service onglet vue d'ensemble", details: ["Client, installation, priorite, description"] },
    3: { caption: "Onglet Jobs groupe par installation", details: ["Titre, code, statut, type de travail"] },
    4: { caption: "Onglet Dispatches", details: ["Numero dispatch, technicien, date/heure planifiee, priorite"] },
    5: { caption: "Journal Temps et Depenses", details: ["Lie au dispatch source", "Heures, saisies de cout"] },
    6: { caption: "Onglet Materiaux utilises", details: ["Articles deduits du catalogue de stock"] },
    7: { caption: "Vue carte des ordres de service", details: ["Epingles de geolocalisation", "Navigation Ouvrir dans Maps"] },
  },
  'module-hr': {
    1: { caption: "Annuaire des employes", details: ["Segmentation preparation a la paie", "Recherche et filtre departement"] },
    2: { caption: "Execution de la paie resume mensuel", details: ["Baremes CNSS, CSS, IRPP", "Generation de bulletins de salaire PDF"] },
    3: { caption: "Vue matrice des presences", details: ["Heures travaillees, heures sup, retards par employe"] },
    4: { caption: "Workflow de demande de conge", details: ["Vue calendrier", "Flux d'approbation manager"] },
    5: { caption: "Declaration CNSS export mensuel", details: ["Export CSV pour portail CNSS", "Taux par employe"] },
    6: { caption: "Organigramme hierarchie departements", details: ["Avatars managers", "Arborescence hierarchique"] },
    7: { caption: "Pipeline de recrutement Kanban", details: ["Candidature a Presélection a Entretien a Offre a Embauche"] },
  },
  'module-dynamic-forms': {
    1: { caption: "Liste des formulaires brouillons et publies", details: ["Puces de statut : Brouillon / Publie / Archive", "Lien public"] },
    2: { caption: "Constructeur de formulaires canevas glisser-deposer", details: ["15+ types de champs", "Panneau d'apercu en direct"] },
    3: { caption: "Constructeur de formulaires parametres du champ", details: ["Libelle, espace reserve, obligatoire, validation"] },
    4: { caption: "Formulaire public vue utilisateur final", details: ["Selecteur de langue EN/FR", "Interface de soumission"] },
    5: { caption: "Boite de reception des reponses", details: ["Export CSV/Excel", "PDF par reponse"] },
  },
  'module-workflow': {
    1: { caption: "Canevas de workflow editeur React-Flow", details: ["Panoramique/zoom, mini-carte, magnétisme grille", "Selection multiple, annuler/retablir"] },
    2: { caption: "Configuration du noeud declencheur", details: ["Webhook, Planifie CRON, Changement de statut, Entite creee"] },
    3: { caption: "Noeud d'action Envoyer email", details: ["Editeur de modele", "Mappage de champs dynamiques"] },
    4: { caption: "Constructeur de workflow IA", details: ["Generation de graphe par langage naturel"] },
    5: { caption: "Debogueur d'execution en direct", details: ["Noeuds codes par couleur", "JSON entree/sortie par etape"] },
    6: { caption: "Liste de l'historique d'execution", details: ["Statut, duree, declenche par"] },
  },
  'module-external': {
    1: { caption: "Liste des endpoints externes", details: ["URL slug unique par endpoint", "Gestion des cles API"] },
    2: { caption: "Configuration de l'endpoint", details: ["Methodes HTTP autorisees", "Validation JSON Schema optionnelle"] },
    3: { caption: "Journal entrant apercu du payload", details: ["Date/heure, Methode, IP source, Code statut"] },
    4: { caption: "Convertir le payload en enregistrement CRM", details: ["Creation en un clic : Offre / Vente / Contact"] },
  },
  'module-lookups': {
    1: { caption: "Listes de reference mise en page deux volets", details: ["Navigation des categories a gauche", "Liste des elements a droite"] },
    2: { caption: "Elements de categorie ajouter et modifier", details: ["Nom, activation, ordre de tri, etoile par defaut"] },
  },
  'module-scheduling': {
    1: { caption: "Dispatcheur chronologie swimlane", details: ["Lignes techniciens x colonnes heures", "Horizons 1j a 30j"] },
    2: { caption: "Vue calendrier mensuel", details: ["Avatars techniciens par jour", "Grille 30 jours"] },
    3: { caption: "Replanification par glisser-deposer", details: ["Deplacer la pastille vers un nouveau creneau ou technicien"] },
    4: { caption: "Panneau des ordres de service non assignes", details: ["Panneau lateral droit avec recherche", "Glisser pour assigner"] },
  },
  'module-settings': {
    1: { caption: "Parametres profil personnel", details: ["Avatar, nom d'affichage, langue, fuseau horaire"] },
    2: { caption: "Parametres entreprise identite visuelle", details: ["Logo, raison sociale, numero fiscal, devise par defaut"] },
    3: { caption: "Preferences theme et couleur d'accentuation", details: ["Theme Clair / Sombre / Systeme", "Selecteur de couleur"] },
    4: { caption: "Gestion des utilisateurs roles et permissions", details: ["Matrice de permissions RBAC par module"] },
    5: { caption: "Abonnement plan et facturation", details: ["Details du plan, utilisation, historique de facturation"] },
  },
};
